-- vim.cmd('colorscheme embark')
-- vim.cmd("autocmd vimenter * hi normal ctermbg=none guibg=none")
-- vim.keymap.set('n', '<Tab>', '<Cmd>BufferLineCycleNext<CR>', {})
-- vim.keymap.set('n', '<S-Tab>', '<Cmd>BufferLineCyclePrev<CR>', {})
